"""
YouTube Channel Popular Shorts Downloader
==========================================
1. For each channel, fetches the most popular Shorts links (sorted by view count).
2. Writes all collected links to links.txt.
3. Runs yt-dlp to download them all.

Requirements:
    pip install yt-dlp requests

Usage:
    python download_channel_videos.py
"""

import os
import subprocess
import sys
import yt_dlp

# ─── CONFIG ───────────────────────────────────────────────────────────────────

# Using local executables in the same folder
YTDLP_BIN = r".\yt-dlp.exe"

# How many top popular shorts to grab per channel (None = grab all available)
MAX_VIDEOS_PER_CHANNEL = 46

# Output file for all collected links
LINKS_FILE = "links.txt"

# Download output folder structure
OUTPUT_TEMPLATE = "%(uploader)s/%(title)s.%(ext)s"

COOKIES_FILE = "cookies.txt"

# ─── COOKIES ──────────────────────────────────────────────────────────────────

COOKIES_CONTENT = """# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.
.youtube.com	TRUE	/	TRUE	1797249500	DEVICE_INFO	ChxOell4T0RnME5UZzRRME1UUTJORFUJTmpZME5nPT0ENyXytEGGPan7s0G
.youtube.com	TRUE	/	TRUE	1808460720	LOGIN_INFO	AFmmF2swRQIgEnj2ljtMeL9xfSvGE1--hPGjuZOsjZpLm4ic1eOALWUCIQCx67fCaab-UZJ5xiHAHDPRoC72vx2S5HJ0Vb4MqoBKDw:QUQ3MjNmekJQVzNjcVVQVHVZQ2hvU3JoanNGY2hDTnhCWW0zUk41bmJSV1dGZGtmSTdZMEdSZ3NvMEd6VXVnRV9JR1ltR0VKclM1WXVaMFVYbkk1YXNkcGliT014aXVtTld1cUhvdXl0RGJIS1ZOc3BwbVkwRE1KMVAwaG5hTXdnUy1BQ3dhT0NHb2g3a3RrVmlqVGJYN0xKVWNBY1Q1RzRn
.youtube.com	TRUE	/	FALSE	0	PREF	f6=40000080&tz=UTC&f4=4000000&hl=en
.youtube.com	TRUE	/	TRUE	1808460719	SAPISID	Pxxs3A8KbJucC645/AWyxluV8xsreu1fMX
.youtube.com	TRUE	/	TRUE	1808460719	SSID	AbAhxDZuqXZFouuzj
.youtube.com	TRUE	/	TRUE	1815825500	VISITOR_PRIVACY_METADATA	CgJOTBIiEh4SHAsMDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicgbA%3D%3D
.youtube.com	TRUE	/	TRUE	0	YSC	tHZzfBToqHM
.youtube.com	TRUE	/	TRUE	1796780557	YT_DEVICE_MEASUREMENT_ID	ykdXbR4=
.youtube.com	TRUE	/	TRUE	1842753911	__Secure-1PAPISID	Pxxs3A8KbJucC645/AWyxluV8xsreu1fMX
.youtube.com	TRUE	/	TRUE	1842753911	__Secure-1PSID	g.a000-QjxC1pcf8WFuv-ur5a3bWTLNjBaFu-NnIxqgoyIrDlPdtEXMVtEB1Gt5duFM0rkLRoZowACgYKASQSARYSFQHGX2MiLt5F-5ytvZvvYFfvyHq1fhoVAUF8yKrmRGd3eEFTsvdRzKyW559x0076
.youtube.com	TRUE	/	TRUE	1813233500	__Secure-1PSIDCC	AKEyXzVRMASHNYULhNEiwGRHZDT-9MpyhAMv-YNQgAgi9rkhzp3qJoX56A2CLnKe0VnNZ_OzyQ
.youtube.com	TRUE	/	TRUE	1805436719	__Secure-1PSIDTS	sidts-CjUBBj1CYjSM8uF57hpFN5IpaVLTLm5u6UqVx54QW3taCJ44EaKnh8lX2USQg51JL8NrcYIlHBAA
.youtube.com	TRUE	/	TRUE	1842753911	__Secure-3PAPISID	Pxxs3A8KbJucC645/AWyxluV8xsreu1fMX
.youtube.com	TRUE	/	TRUE	1842753911	__Secure-3PSID	g.a000-QjxC1pcf8WFuv-ur5a3bWTLNjBaFu-NnIxqgoyIrDlPdtEX1B6VVO-vmjfDWvAsYK_3hQACgYKAaQSARYSFQHGX2Mig5pRbMWuhQGktHynPS3gdRoVAUF8yKrSdXeIWExNsifa7kBAh9FN0076
.youtube.com	TRUE	/	TRUE	1813233500	__Secure-3PSIDCC	AKEyXzW7RCsDQYykXVAcVQRIWhrCnbBkY5-ZXbRYLA_UAcbaKnp40l1nVA2x44_-aTzKhcA1ug
.youtube.com	TRUE	/	TRUE	1805436719	__Secure-3PSIDTS	sidts-CjUBBj1CYjSM8uF57hpFN5IpaVLTLm5u6UqVx54QW3taCJ44EaKnh8lX2USQg51JL8NrcYIlHBAA
.youtube.com	TRUE	/	TRUE	1797248434	__Secure-ROLLOUT_TOKEN	CJnh-Kab1omNORCiiq-zp6uTAxiIq7m4mI6VAw%3D%3D
.youtube.com	TRUE	/	TRUE	1815825499	__Secure-YEC	CgtNODdjbFpweGhCcyjcl8rRBjIoCgJOTBIiEh4SHAsMDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicgbGLgAgrdAjE2LllURT1DMldBWVYtLTVYTG5VXzRPVGtPTERwdXVVWW8tUUVWOHNGalhmb3ZwVlF4dlQwdS0wQ1BUc1p0R2pPRXVWQXdvRXZRVVl2Rmx0NktYS2ExaGJ1UGdfR0FSSEJxM1VrczM0cXN3ZDgyVlIzb0hiVngwcG5QN0I5UktmazFXVENaY0hJbVg0VVMyMDZSRm9yamJYZEM0RHRGV1ZUQzh2b0hwOVVuOGs2dkpVZDF2RGd4NFZRVEhfbkkxdWhOLTJxazFDaEN0MFJrckRSM0pESHhKdWF6RVNvcDhpWjVUQzNRSDJMV1BMTTBJa1FQdExkVnNfNlpzdGc2bUVUQUlnTjItdnU2TmJINjRhb2M2emx2NWZqdTlKdzlQMTdOcnpwVUFGaGh6dU40cHI4dmxKU2xnUF9tM015UFdLZUZlVzIybWd2Q1UyOEk3VW5TRWJtNUJwT0ZrVFE%3D
.youtube.com	TRUE	/	TRUE	1844769500	__Secure-YT_TVFAS	t=492750&s=3
.youtube.com	TRUE	/tv	TRUE	1814529500	__Secure-YT_DERP	CIHm-q-KBA%3D%3D
"""

# ─── CHANNELS ─────────────────────────────────────────────────────────────────

CHANNELS = [
    "https://www.youtube.com/@GizaToys",
    "https://www.youtube.com/@manstuffusa"
]

# ──────────────────────────────────────────────────────────────────────────────


def write_cookies():
    """Write cookies to file if it doesn't already exist."""
    if not os.path.exists(COOKIES_FILE):
        with open(COOKIES_FILE, "w", encoding="utf-8") as f:
            f.write(COOKIES_CONTENT.strip() + "\n")
        print(f"[+] Created {COOKIES_FILE}")


def get_popular_shorts(channel_url: str, max_count) -> list[str]:
    """
    Fetch video URLs from a channel's Shorts tab, sorted by view count (popular first).
    Fetches ALL videos first, then sorts and slices so we actually get the most viewed.
    Falls back to /videos and bare URL if /shorts tab doesn't exist.
    """
    tabs = ["/shorts", "/videos", "/featured", ""]
    ydl_opts = {
        "quiet": True,
        "no_warnings": True,
        "ignoreerrors": True,
        "extract_flat": "in_playlist",
        # No playlistend — fetch everything so sort is accurate
    }

    for tab in tabs:
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(channel_url + tab, download=False)

            if not info or not info.get("entries"):
                continue

            entries = [e for e in info["entries"] if e]
            if not entries:
                continue

            # Sort by view count descending (most popular first)
            entries.sort(key=lambda e: e.get("view_count") or 0, reverse=True)

            # Now take the top N after sorting
            if max_count:
                entries = entries[:max_count]

            urls = []
            for entry in entries:
                vid_id = entry.get("id") or entry.get("url", "")
                if vid_id:
                    if vid_id.startswith("http"):
                        urls.append(vid_id)
                    else:
                        urls.append(f"https://www.youtube.com/watch?v={vid_id}")

            if urls:
                return urls

        except Exception:
            continue

    return []


def collect_all_links() -> list[str]:
    """Loop through all channels and collect popular shorts links."""
    all_links = []
    seen = set()

    for i, channel_url in enumerate(CHANNELS, 1):
        handle = channel_url.split("@")[-1]
        print(f"[{i}/{len(CHANNELS)}] Fetching popular shorts: {handle}", end=" ... ", flush=True)

        links = get_popular_shorts(channel_url, MAX_VIDEOS_PER_CHANNEL)

        # Deduplicate
        new_links = [l for l in links if l not in seen]
        seen.update(new_links)
        all_links.extend(new_links)

        if new_links:
            print(f"found {len(new_links)} videos")
        else:
            print("NONE FOUND")

    return all_links


def save_links(links: list[str]):
    """Save all links to links.txt, one per line."""
    with open(LINKS_FILE, "w", encoding="utf-8") as f:
        for link in links:
            f.write(link + "\n")
    print(f"\n[+] Saved {len(links)} links to {LINKS_FILE}")


def run_download():
    """Run yt-dlp to download all videos from links.txt."""
    print("\n[+] Starting download with yt-dlp...\n")

    cmd = [
        YTDLP_BIN,
        "-ia", LINKS_FILE,
        "-N", "1",
        "--sleep-interval", "10",
        "--download-archive", "history.txt",
        "-f", "bv+ba/b",
        "--merge-output-format", "mp4",
        "--cookies", COOKIES_FILE,
        "--js-runtime", "deno",
        "--user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "--extractor-args", "youtube:player_client=web_creator",
        "-o", OUTPUT_TEMPLATE,
    ]

    print("Command:", " ".join(cmd))
    print("-" * 60)

    try:
        subprocess.run(cmd, check=False)
    except FileNotFoundError:
        print(f"\n[ERROR] Could not find yt-dlp at '{YTDLP_BIN}'.")
        print("Make sure yt-dlp is installed (pip install yt-dlp) or set YTDLP_BIN")
        print("to the full path of your yt-dlp.exe, e.g.:")
        print('    YTDLP_BIN = r".\\yt-dlp.exe"')
        sys.exit(1)


def main():
    write_cookies()

    print(f"Collecting popular Shorts from {len(CHANNELS)} channels...\n")
    links = collect_all_links()

    if not links:
        print("\n[!] No links found. Exiting.")
        sys.exit(0)

    save_links(links)

    answer = input("\nStart downloading now? [Y/n]: ").strip().lower()
    if answer in ("", "y", "yes"):
        run_download()
    else:
        print(f"Skipped download. Run manually:")
        print(f'  {YTDLP_BIN} -ia {LINKS_FILE} --cookies {COOKIES_FILE} -o "{OUTPUT_TEMPLATE}"')


if __name__ == "__main__":
    main()
